from io import BytesIO
import textwrap

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

PAGE_WIDTH, PAGE_HEIGHT = A4
LEFT_MARGIN = 18 * mm
RIGHT_MARGIN = 18 * mm
TOP_MARGIN = 18 * mm
BOTTOM_MARGIN = 18 * mm
CONTENT_WIDTH = PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN


def generate_project_pdf(report_data: dict) -> BytesIO:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    pdf.setTitle(f'{report_data["project"]["project_name"]} - Readiness Report')

    state = {
        "page_number": 1,
        "y": PAGE_HEIGHT - TOP_MARGIN,
    }

    project = report_data["project"]
    dashboard = report_data["dashboard"]
    controls = report_data["controls"]
    evidence = report_data["evidence"]
    findings = report_data["findings"]
    remediation_tasks = report_data["remediation_tasks"]

    # Optional metadata with safe defaults
    assessor = project.get("assessor", "Patrick Adefowora")
    scope = project.get(
        "scope",
        "AWS Cloud Environment (IAM, S3, EC2, Logging, Network Security)",
    )

    def draw_page_header():
        pdf.setFont("Helvetica-Bold", 9)
        pdf.setFillColor(colors.HexColor("#1F2937"))
        pdf.drawString(LEFT_MARGIN, PAGE_HEIGHT - 12 * mm, "Cloud Compliance Readiness Toolkit")

        pdf.setFont("Helvetica", 8)
        pdf.setFillColor(colors.grey)
        pdf.drawRightString(
            PAGE_WIDTH - RIGHT_MARGIN,
            PAGE_HEIGHT - 12 * mm,
            f'Project: {project["project_name"]}',
        )

        pdf.setStrokeColor(colors.HexColor("#D1D5DB"))
        pdf.line(
            LEFT_MARGIN,
            PAGE_HEIGHT - 14 * mm,
            PAGE_WIDTH - RIGHT_MARGIN,
            PAGE_HEIGHT - 14 * mm,
        )

    def draw_page_footer():
        pdf.setStrokeColor(colors.HexColor("#E5E7EB"))
        pdf.line(LEFT_MARGIN, 12 * mm, PAGE_WIDTH - RIGHT_MARGIN, 12 * mm)

        pdf.setFont("Helvetica", 8)
        pdf.setFillColor(colors.grey)
        pdf.drawString(LEFT_MARGIN, 8 * mm, "Generated by Cloud Compliance Readiness Toolkit")
        pdf.drawRightString(PAGE_WIDTH - RIGHT_MARGIN, 8 * mm, f"Page {state['page_number']}")

    def new_page():
        draw_page_footer()
        pdf.showPage()
        state["page_number"] += 1
        state["y"] = PAGE_HEIGHT - TOP_MARGIN
        draw_page_header()

    def ensure_space(required_height: float):
        if state["y"] - required_height < BOTTOM_MARGIN + 10 * mm:
            new_page()

    def draw_wrapped_text(
            text: str,
            font: str = "Helvetica",
            size: int = 10,
            color=colors.black,
            indent: float = 0,
            extra_gap: float = 2,
            max_chars: int = 95,
    ):
        wrapped = textwrap.wrap(text or "", width=max_chars)
        if not wrapped:
            wrapped = [""]

        needed = len(wrapped) * (size + 3) + extra_gap
        ensure_space(needed)

        pdf.setFont(font, size)
        pdf.setFillColor(color)

        x = LEFT_MARGIN + indent
        for line in wrapped:
            pdf.drawString(x, state["y"], line)
            state["y"] -= size + 3

        state["y"] -= extra_gap

    def draw_section_title(title: str):
        ensure_space(18)
        state["y"] -= 3
        pdf.setFillColor(colors.HexColor("#0F172A"))
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(LEFT_MARGIN, state["y"], title)
        state["y"] -= 6

        pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
        pdf.line(LEFT_MARGIN, state["y"], PAGE_WIDTH - RIGHT_MARGIN, state["y"])
        state["y"] -= 10

    def draw_summary_box(dashboard_data: dict):
        box_height = 42 * mm
        ensure_space(box_height + 5)

        x = LEFT_MARGIN
        y = state["y"]
        w = CONTENT_WIDTH
        h = box_height

        pdf.setFillColor(colors.HexColor("#F8FAFC"))
        pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
        pdf.roundRect(x, y - h, w, h, 6, fill=1, stroke=1)

        pdf.setFont("Helvetica-Bold", 12)
        pdf.setFillColor(colors.HexColor("#111827"))
        pdf.drawString(x + 8, y - 14, "Executive Summary")

        pdf.setFont("Helvetica", 10)
        pdf.setFillColor(colors.black)
        pdf.drawString(x + 8, y - 28, f"Readiness Percentage: {dashboard_data['readiness_percentage']}%")
        pdf.drawString(x + 8, y - 42, f"Readiness Level: {dashboard_data.get('readiness_level', 'N/A')}")
        pdf.drawString(x + 8, y - 56, f"Total Controls: {dashboard_data['total_controls']}")

        pdf.drawString(x + 190, y - 28, f"Evidence Count: {dashboard_data['evidence_count']}")
        pdf.drawString(x + 190, y - 42, f"Open Findings: {dashboard_data['open_findings']}")
        pdf.drawString(x + 190, y - 56, f"Open Remediation Tasks: {dashboard_data['open_remediation_tasks']}")

        state["y"] -= h + 8

    def draw_risk_summary_box(findings_data: list[dict]):
        severity_counts = {
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
        }

        for item in findings_data:
            sev = (item.get("severity") or "").lower()
            if sev in severity_counts:
                severity_counts[sev] += 1

        box_height = 34 * mm
        ensure_space(box_height + 5)

        x = LEFT_MARGIN
        y = state["y"]
        w = CONTENT_WIDTH
        h = box_height

        pdf.setFillColor(colors.HexColor("#FFF7ED"))
        pdf.setStrokeColor(colors.HexColor("#FED7AA"))
        pdf.roundRect(x, y - h, w, h, 6, fill=1, stroke=1)

        pdf.setFont("Helvetica-Bold", 12)
        pdf.setFillColor(colors.HexColor("#9A3412"))
        pdf.drawString(x + 8, y - 14, "Risk Summary")

        pdf.setFont("Helvetica", 10)
        pdf.setFillColor(colors.black)
        pdf.drawString(x + 8, y - 30, f'Critical Risks: {severity_counts["critical"]}')
        pdf.drawString(x + 8, y - 44, f'High Risks: {severity_counts["high"]}')
        pdf.drawString(x + 170, y - 30, f'Medium Risks: {severity_counts["medium"]}')
        pdf.drawString(x + 170, y - 44, f'Low Risks: {severity_counts["low"]}')

        state["y"] -= h + 8

    def draw_bullet(text: str, severity: str | None = None):
        color = colors.black
        if severity:
            sev = severity.lower()
            if sev == "critical":
                color = colors.HexColor("#991B1B")
            elif sev == "high":
                color = colors.HexColor("#B45309")
            elif sev == "medium":
                color = colors.HexColor("#1D4ED8")
            elif sev == "low":
                color = colors.HexColor("#166534")

        ensure_space(18)
        pdf.setFillColor(color)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(LEFT_MARGIN, state["y"], "•")
        pdf.setFillColor(colors.black)
        draw_wrapped_text(
            text,
            font="Helvetica",
            size=10,
            indent=10,
            extra_gap=1,
            max_chars=88,
        )

    def draw_cover():
        draw_page_header()

        state["y"] = PAGE_HEIGHT - 35 * mm
        pdf.setFont("Helvetica-Bold", 18)
        pdf.setFillColor(colors.HexColor("#0F172A"))
        pdf.drawString(LEFT_MARGIN, state["y"], "Cloud Compliance Readiness Report")

        state["y"] -= 12
        pdf.setFont("Helvetica", 11)
        pdf.setFillColor(colors.HexColor("#475569"))
        pdf.drawString(LEFT_MARGIN, state["y"], "Portfolio-ready compliance assessment export")

        state["y"] -= 18

        pdf.setFillColor(colors.HexColor("#F8FAFC"))
        pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
        pdf.roundRect(LEFT_MARGIN, state["y"] - 40 * mm, CONTENT_WIDTH, 40 * mm, 6, fill=1, stroke=1)

        pdf.setFont("Helvetica-Bold", 12)
        pdf.setFillColor(colors.HexColor("#111827"))
        pdf.drawString(LEFT_MARGIN + 8, state["y"] - 10, "Project Details")

        pdf.setFont("Helvetica", 10)
        pdf.drawString(LEFT_MARGIN + 8, state["y"] - 24, f'Project: {project["project_name"]}')
        pdf.drawString(LEFT_MARGIN + 8, state["y"] - 38, f'Client: {project["client_name"]}')
        pdf.drawString(LEFT_MARGIN + 8, state["y"] - 52, f'Status: {project["status"]}')
        pdf.drawString(LEFT_MARGIN + 8, state["y"] - 66, f"Assessor: {assessor}")

        pdf.drawString(LEFT_MARGIN + 240, state["y"] - 24, f'Readiness: {dashboard["readiness_percentage"]}%')
        pdf.drawString(LEFT_MARGIN + 240, state["y"] - 38, f'Level: {dashboard.get("readiness_level", "N/A")}')

        state["y"] -= 50 * mm

        draw_summary_box(dashboard)
        draw_risk_summary_box(findings)

        draw_section_title("Assessment Context")
        draw_wrapped_text(
            project.get("description") or "No project description provided.",
            font="Helvetica",
            size=10,
            max_chars=95,
        )
        draw_wrapped_text(
            f"Scope: {scope}",
            font="Helvetica",
            size=10,
            color=colors.HexColor("#334155"),
            max_chars=95,
        )

    draw_cover()

    draw_section_title("Control Overview")
    for item in controls:
        draw_bullet(
            f'{item["control_code"]} - {item["control_title"]} | '
            f'Status: {item["status"]} | '
            f'Validation: {item["validation_status"]} | '
            f'Readiness Score: {item["readiness_score"]}'
        )
        if item.get("implementation_notes"):
            draw_wrapped_text(
                f'Notes: {item["implementation_notes"]}',
                font="Helvetica-Oblique",
                size=9,
                color=colors.HexColor("#475569"),
                indent=10,
                max_chars=86,
            )

    draw_section_title("Evidence Summary")
    if evidence:
        for item in evidence:
            line = (
                f'Control {item["control_id"]}: {item["title"]} | '
                f'Type: {item["evidence_type"]} | '
                f'Source: {item.get("source") or "N/A"} | '
                f'Status: {item["status"]}'
            )
            draw_bullet(line)
    else:
        draw_wrapped_text("No evidence records were found for this project.", size=10)

    draw_section_title("Findings Summary")
    if findings:
        for item in findings:
            draw_bullet(
                f'[{item["severity"].upper()}] Control {item["control_id"]}: {item["title"]}',
                severity=item["severity"],
            )
            draw_wrapped_text(
                f'Description: {item["description"]}',
                size=9,
                indent=10,
                max_chars=86,
            )
            draw_wrapped_text(
                f'Recommendation: {item.get("recommendation") or "N/A"}',
                size=9,
                indent=10,
                color=colors.HexColor("#334155"),
                max_chars=86,
            )
    else:
        draw_wrapped_text("No findings were recorded for this project.", size=10)

    draw_section_title("Remediation Plan")
    if remediation_tasks:
        for item in remediation_tasks:
            draw_bullet(
                f'Finding {item["finding_id"]}: {item["title"]} | '
                f'Priority: {item["priority"]} | '
                f'Owner: {item.get("owner") or "Unassigned"} | '
                f'Status: {item["status"]}'
            )
    else:
        draw_wrapped_text("No remediation tasks were recorded for this project.", size=10)

    draw_section_title("Conclusion")
    draw_wrapped_text(
        "The assessment identified partial implementation of key cloud security controls, "
        "with significant gaps remaining in privileged access management and storage "
        "security. Immediate remediation is recommended for critical exposure risks. "
        "Overall readiness is currently "
        f'{dashboard.get("readiness_level", "N/A")}, and further control validation is '
        "required prior to compliance certification.",
        size=10,
        max_chars=95,
    )

    draw_page_footer()
    pdf.save()
    buffer.seek(0)
    return buffer
